### ISSUE TITLE
How to add Reference to Connected Service

### ISSUE THREAD

**Issue by ghost** [JuergenSchwertl/AzureSphereSamples#12]
Dear Sir,

Trying to add as explained the reference to IoT Hub Connected Service, I don;t see anything like Reference in the solution explorer, would it be possible to give a complete example? Remmber Reference in SLN solutions but don't see it in CMAke.

Thanks in advance!

Erik

**Comment by JuergenSchwertl** [comment]
The "Connect to Service" wizard is not available  on CMake projects. I've updated the sample to point to the Azure Portal blades.
Sorry for the delay in response.
